<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
	  <UseWindowsForms>true</UseWindowsForms>
	  <RootNamespace>SpotifyMediaKey</RootNamespace>
	<AssemblyName>Spotify-MediaKey</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Logo.ico</ApplicationIcon>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Window1.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>


  <ItemGroup>
    <Page Remove="Window1.xaml" />
  </ItemGroup>

</Project>
